import { PermianBackground } from '../../backgrounds';
import type { ThemeDefinition } from '../../types';

export const permian: ThemeDefinition = {
  id: 'permian',
  variant: 'dark',
  hasLightVariant: true,
  label: 'Permian',
  icon: '🛢️',
  description: 'Oilpatch dusk-to-noon',
  appName: 'SLOPCAST',
  appSubtitle: 'Patch Economics',
  chartPalette: {
    oil: '#E87030',
    cash: '#00E890',
    lav: '#F0C020',
    grid: 'rgba(0, 232, 144, 0.14)',
    text: '#9AA99A',
    surface: '#0A1F18',
    border: 'rgba(45, 107, 74, 0.42)',
  },
  mapPalette: {
    gridColor: '#2D6B4A',
    gridOpacity: 0.32,
    selectedStroke: '#E87030',
    glowColor: '#00E890',
    unassignedFill: '#556070',
    lassoFill: 'rgba(240, 192, 32, 0.14)',
    lassoStroke: '#F0C020',
    lassoDash: '6, 3',
    mapboxOverrides: {
      bgColor: '#0A1F18',
      waterColor: '#14654A',
      landColor: '#1A3A2A',
      labelColor: '#6B8870',
      roadOpacity: 0.14,
    },
  },
  features: {
    retroGrid: false,
    brandFont: true,
    glowEffects: true,
    panelStyle: 'glass',
    headingFont: true,
    denseSpacing: false,
    isClassicTheme: false,
  },
  BackgroundComponent: PermianBackground,
  atmosphereClass: 'theme-atmo',
  headerAtmosphereClass: 'theme-atmo-header',
  atmosphericOverlays: ['theme-atmo-bands', 'theme-atmo-horizon', 'theme-atmo-ridges', 'theme-atmo-heat'],
  fxTheme: true,
  tokens: {
    dark: {
      color: {
        bgDeep: '10 31 24',
        bgSpace: '16 46 36',
        surface1: '22 54 42',
        surface2: '34 72 56',
        border: '58 102 80',
        cyan: '0 232 144',
        magenta: '232 112 48',
        lav: '240 192 32',
      },
      radius: {
        panel: '12px',
        inner: '6px',
      },
      typography: {
        fontSans: "'Inter', sans-serif",
        fontHeading: "'Barlow Condensed', 'Syne', sans-serif",
        fontBrand: "'Syne', 'Inter', sans-serif",
        fontScript: "'Permanent Marker', cursive",
      },
    },
    light: {
      color: {
        bgDeep: '188 218 196',
        bgSpace: '206 228 212',
        surface1: '226 240 228',
        surface2: '212 230 216',
        border: '92 130 104',
        cyan: '0 160 108',
        magenta: '214 92 40',
        lav: '196 148 28',
      },
      radius: {
        panel: '12px',
        inner: '6px',
      },
      typography: {
        fontSans: "'Inter', sans-serif",
        fontHeading: "'Barlow Condensed', 'Syne', sans-serif",
        fontBrand: "'Syne', 'Inter', sans-serif",
        fontScript: "'Permanent Marker', cursive",
      },
    },
  },
};
